let data = [
	{
		productTitle: 'Gate of Truth',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/gate-of-truth.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Evangelion',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/evangelion.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Tardis',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/tardis.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'The One Ring',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/the-one-ring.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'R2D2',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/r2d2.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'C3PO',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/c3po.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Philosopher's Stone",
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/philosphers-stone.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Sword of Godric Gryffindor',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/sword-gryffindor.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Khyber Saber',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/khyber-saber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Mace Windu's Saber",
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/mace-windu-light-saber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Command Block',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/command-block.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Dark Saber',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/dark-saber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Morty',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/morty.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Darth Revan's Mask",
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/darth-revan-mask.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Omnitrix',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/ominitrix.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Ultimatrix',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/ultimatrix.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Biomnitrix',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/biomnitrixs.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Good ol' Wooden Sword",
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/wooden-sword.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Delorean Time Machine',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/delorean-time-machine.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Hoverboard',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/hoverboard.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Death Note',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/death-note.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Diamond Armour Set',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/diamond-armour.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Endor Dragon',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/endor-dragon.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Heart of Davy Jones',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/heart-of-davy-jones.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Magical Compass',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/magical-compass.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Green Lantern's Ring",
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/green-lantern-ring.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Higher Ground',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/high-ground.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Nimbus 2000',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/nimbus.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Portal Gun',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/portal-gun.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Pokeball',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/pokeball.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Resurrection Stone',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/resurrection-stone.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Dragon Balls',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/dragon-balls.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Death Star',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/death-star.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Elder Wand',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/elder-wand.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Celestialsapien',
		productImgSrc: 'https://raw.githubusercontent.com/pulkit-jasti/Pandora-store/master/src/assets/product-images/celestialsapien.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
];

export default data;
