let data = [
	{
		productTitle: 'Gate of Truth',
		productImgSrc: './assets/product-images/gate-of-truth.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Dark Saber',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Evangelion',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Tardis',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'The One Ring',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Philosopher's Stone",
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Sword of Godric Gryffindor',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Khyber Saber',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Command Block',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Dark Saber',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Morty',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Darth Revan's Mask",
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Omnitrix',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Ultimatrix',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Biomnitrix',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Good ol' Wooden Sword",
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Delorean Time Machine',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Hoverboard',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Death Note',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Diamond Armour Set',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Endor Dragon',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Heart of Davy Jones',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: "Green Lantern's Ring",
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Higher Ground',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Nimbus 2000',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Portal Gun',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Pokeball',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Resurrection Stone',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
	{
		productTitle: 'Dragon Balls',
		productImgSrc: './assets/product-images/darksaber.png',
		productCost: '100 Units',
		productDes: 'lorem ipsum',
	},
];

export default data;
